id: P000063
initial_creation_type: ebook
source_metadata:
  title: རྒྱུད་འགྲེལ།
  authors:
  - མཛད་པ་པོ། དྲི་བྲལ་ཉི་མའི་སྣང་བ།
  layers:
  - book_title
  - author
  - chapter_title
  - quotation
  - sabche
  - yigchung
  id: SHE-001
web_metadata:
  title:
    en: A Commentary on a Tantra
    bo: རྒྱུད་འགྲེལ།
  collection:
    en: Shechen Tantra Series–  Book 1
    bo: ''
  author:
    en: Dridral Nyimai Nangwa
    bo: དྲི་བྲལ་ཉི་མའི་སྣང་བ།
  pusblisher:
    en: Shechen Publications
    bo: ཞེ་ཆེན་བསྟན་གཉིས་དར་རྒྱས་གླིང།
  sku: SHE-001
  category:
    en: Uncategorized
    bo: Uncategorized @tib
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: SHE-001.epub
  description:
    en: ''
    bo: ''
